version: "2"

services:
  pdns:
    image: johnyb/pdns-minimal
    ports:
      - "53:53/udp"
  pdnsui:
    build: .
    image: johnyb/yapdnsui
    command: "yarn dev"
    links:
      - "pdns:pdns"
    ports:
      - "8080:8080"
    volumes:
      - ".:/app/yapdnsui"
