version: "2"

services:
  pdns:
    image: johnyb/pdns-minimal
    networks:
      default:
        aliases:
          - pdns
    command: "--allow-axfr-ips=0.0.0.0/0,::/0"
  pdns_slave:
    image: johnyb/pdns-minimal
    networks:
      default:
        aliases:
          - pdns_slave
    command: "--slave"
  pdns_rec:
    image: johnyb/pdns-minimal
    networks:
      default:
        aliases:
          - pdns_rec
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    entrypoint: pdns_recursor
    command: ""
  pdnsui:
    build: .
    image: johnyb/yapdnsui
    links:
      - pdns
      - pdns_slave
    command: "yarn dev"
    ports:
      - "3000:8080"
    volumes:
      - ".:/app/yapdnsui"
