version: "2"

services:
  pdns:
    image: johnyb/pdns-minimal
  pdnsui:
    build: .
    environment:
      - "PORT=8080"
      - "DEBUG=yapdnsui"
    links:
      - "pdns:pdns"
    ports:
      - "8080:8080"
    command: "nodemon"
    volumes:
      - ".:/app/yapdnsui"
